# Generated by Django 4.1.5 on 2023-01-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorStatus',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=10)),
            ],
            options={
                'db_table': 'elevator_status',
            },
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('location', models.CharField(db_column='location', max_length=50, null=True)),
                ('current_floor', models.IntegerField(db_column='current_floor')),
                ('destination_floor', models.IntegerField(blank=True, db_column='destination_floor', null=True)),
                ('direction', models.BooleanField(blank=True, db_column='direction', null=True)),
                ('working', models.BooleanField(db_column='working')),
                ('min_floor', models.IntegerField(db_column='min_floor')),
                ('max_floor', models.IntegerField(db_column='max_floor')),
                ('max_occupancy', models.IntegerField(db_column='max_occupancy')),
                ('current_occupancy', models.IntegerField(db_column='current_occupancy')),
                ('status', models.ForeignKey(db_column='status', null=True, on_delete=django.db.models.deletion.CASCADE, to='elevator.elevatorstatus')),
            ],
            options={
                'db_table': 'elevator',
            },
        ),
    ]
