# Generated by Django 4.1.5 on 2023-07-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_remove_elevator_working_alter_elevatorstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='current_occupancy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='destination_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='direction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='max_floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='max_occupancy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='min_floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elevator.elevatorstatus'),
        ),
        migrations.AlterField(
            model_name='elevatorstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elevatorstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
