# Generated by Django 4.1.5 on 2023-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_alter_elevator_current_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='door_status',
            field=models.BooleanField(default=True),
        ),
    ]
