# Generated by Django 4.1.5 on 2023-07-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_elevator_door_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='door_status',
            new_name='door_close',
        ),
    ]
