# Generated by Django 4.1.5 on 2023-07-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0005_rename_door_status_elevator_door_close'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='current_occupancy',
            new_name='current_capacity',
        ),
        migrations.RenameField(
            model_name='elevator',
            old_name='max_occupancy',
            new_name='max_capacity',
        ),
        migrations.RenameField(
            model_name='elevator',
            old_name='direction',
            new_name='moving_up',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='location',
        ),
    ]
