# Generated by Django 4.1.5 on 2023-07-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0006_rename_current_occupancy_elevator_current_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='moving_up',
            field=models.BooleanField(default=True),
        ),
    ]
