# Generated by Django 4.1.5 on 2023-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0007_alter_elevator_moving_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='moving_up',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
