# Generated by Django 4.1.5 on 2023-07-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0008_alter_elevator_moving_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
