# Generated by Django 4.1.5 on 2023-07-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0009_elevator_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='location',
            new_name='name',
        ),
    ]
