# Generated by Django 4.1.5 on 2023-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0010_rename_location_elevator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_capacity',
            field=models.IntegerField(null=True),
        ),
    ]
