from django.urls import path, include
from rest_framework import routers
from elevator import views
from .views import ElevatorViewSet

router = routers.DefaultRouter()
router.register(r'lift', views.ElevatorViewSet) # viewset is associated with the URL pattern r'elevator'.

urlpatterns = [
    path('', include(router.urls)), #  includes the URL patterns generated by the router instance
    # path('lift/', ElevatorViewSet.as_view()),
    path('use/', views.use_elevator),
    path('maintenance/', views.elevator_maintenance),
    path('api-auth/', include('rest_framework.urls'))
]