from django.urls import path, include
from rest_framework import routers
from elevator import views

router = routers.DefaultRouter()
router.register(r'elevator', views.ElevatorViewSet) # viewset is associated with the URL pattern r'elevator'.

urlpatterns = [
    path('', include(router.urls)), #  includes the URL patterns generated by the router instance
    path('use/', views.use_elevator),
    path('maintainence/', views.elevator_maintainence),
    path('api-auth/', include('rest_framework.urls'))
]